### ISSUE TITLE
Issue with Renaming Parkour

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [Block2Block/HubParkour#17]
I am trying to rename the parkour, and it does not work.

**Steps to Reproduce**
- Create a parkour (mine has 30 checkpoints)
- do `/parkour edit <name>`
- type `1`
- do `/parkour input <new name>`

After I do these, the holograms disappear, and this shows up in console.
```
[19:09:10 WARN]: [HubParkour] Plugin HubParkour v2.5.6 generated an exception while executing task 5191
java.lang.IllegalArgumentException: Async hologram creation
	at com.gmail.filoghost.holographicdisplays.util.Validator.isTrue(Validator.java:27) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.object.DefaultBackendAPI.createHologram(DefaultBackendAPI.java:40) ~[?:?]
	at com.gmail.filoghost.holographicdisplays.api.HologramsAPI.createHologram(HologramsAPI.java:46) ~[?:?]
	at me.block2block.hubparkour.entities.Parkour.generateHolograms(Parkour.java:162) ~[?:?]
	at me.block2block.hubparkour.entities.Parkour.setName(Parkour.java:224) ~[?:?]
	at me.block2block.hubparkour.entities.EditWizard.onChat(EditWizard.java:95) ~[?:?]
	at me.block2block.hubparkour.commands.CommandParkour$8.run(CommandParkour.java:605) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-792]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-792]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
If I do `/parkour cancel` then type `8` to exit the editor, the holograms come back, but the name is still the same as the old one.

**Server Information**
- Server Version: git-Paper-792 (MC: 1.16.5)
- Plugin Version: 2.5.6

**Comment by Block2Block** [comment]
Thanks for the bug report, will be addressed in the next version.

**Comment by Block2Block** [comment]
Issue fixed in latest version.
