### ISSUE TITLE
SQL 1.18.1 ERROR

### ISSUE THREAD

**Issue by thiagogebrimm** [Block2Block/HubParkour#18]
`[16:47:16 ERROR]: There has been an error accessing the database. Try checking your database is online. Stack trace:
[16:47:16 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[16:47:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[16:47:16 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[16:47:16 WARN]:        at org.sqlite.core.DB.execute(DB.java:881)
[16:47:16 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[16:47:16 WARN]:        at HubParkour-2.6.2.jar//me.block2block.hubparkour.managers.DatabaseManager.addAttempt(DatabaseManager.java:1056)
[16:47:16 WARN]:        at HubParkour-2.6.2.jar//me.block2block.hubparkour.entities.HubParkourPlayer$7.run(HubParkourPlayer.java:221)
[16:47:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:47:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:47:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:47:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:47:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:47:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Block2Block** [comment]
Unfortunately, there is nothing I can do about this as this seems to be an issue with the plugin not being able to close prior connections properly, which only happens when the server doesn't exit cleanly (without shutting down properly allowing plugins to disable themselves). If this is through a hosting provider I'd wait a few hours for the old connection to reset then try again. If this is being hosted independently you can just restart the machine to reset the connection.
