### ISSUE TITLE
dB error 

### ISSUE THREAD

**Issue by thiagogebrimm** [Block2Block/HubParkour#19]
```
[18:09:43 ERROR]: There has been an error accessing the database. Try checking your database is online. Stack trace:
[18:09:43 WARN]: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
[18:09:43 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1030)
[18:09:43 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1042)
[18:09:43 WARN]:        at org.sqlite.core.DB.execute(DB.java:881)
[18:09:43 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
[18:09:43 WARN]:        at HubParkour-2.6.7.jar//me.block2block.hubparkour.managers.DatabaseManager.addAttempt(DatabaseManager.java:1056)
[18:09:43 WARN]:        at HubParkour-2.6.7.jar//me.block2block.hubparkour.entities.HubParkourPlayer$7.run(HubParkourPlayer.java:226)
[18:09:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:09:43 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:09:43 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:09:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:09:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:09:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Block2Block** [comment]
This is caused by the server not closing correctly and therefore keeping an old connection going. Give it a few hours and the issue should resolve itself (or if this is a VPS or a system that you control the OS of, just restart the system). If this still doesn't fix the issue, please feel free to join my support Discord so I can debug further.
