### ISSUE TITLE
support 1.21

### ISSUE THREAD

**Issue by MCFurina** [Block2Block/HubParkour#39]
Paper 1.21 
[14:28:30 ERROR]: Error occurred while enabling HubParkour v2.7.5 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at HubParkour-2.7.5.jar/me.block2block.hubparkour.HubParkour.onEnable(HubParkour.java:69) ~[HubParkour-2.7.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-62-5a503d7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-62-5a503d7]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.21.jar:1.21-62-5a503d7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-62-5a503d7]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by Robotv2** [comment]
https://github.com/Robotv2/HubParkour/releases/tag/2.7.5-FIX

**Comment by Block2Block** [comment]
Fix published as of 2.7.6
