### ISSUE TITLE
Could not pass event PlayerMoveEvent to HubParkour v2.4.1

### ISSUE THREAD

**Issue by Stixil** [Block2Block/HubParkour#5]
[17:45:38 ERROR]: Could not pass event PlayerMoveEvent to HubParkour v2.4.1
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
        at me.block2block.hubparkour.entities.HubParkourPlayer.checkpoint(HubParkourPlayer.java:111) ~[?:?]
        at me.block2block.hubparkour.listeners.PressurePlateListener.onPressurePlate(PressurePlateListener.java:178) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1144]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1144]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1144]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1527) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1144]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1144]
        at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Block2Block** [comment]
This is not an issue with your version, this is an issue with missing configuration values, can you send me a pastebin with your entire config in and what you were doing at the time

**Comment by Bubbycolditz** [comment]
@Stixil The solution to this problem is to have the plugin regenerate your config file. Be sure to have a backup of your old config file and copy the values from the old config to the newly-generated config file.

If you are using SQLite, be sure to keep the **hp-storage.db** file, however if you are using MYSQL, be sure to copy the details in the new config and change the Database Type to **MySQL** on Line 323.

**Comment by Block2Block** [comment]
Issue should be fixed as of latest version. If the issue persists, open a new issue.
