### ISSUE TITLE
Error on new update 2.5:

### ISSUE THREAD

**Issue by thiagogebrimm** [Block2Block/HubParkour#8]
```
[23:42:35 WARN]: [HubParkour] Plugin HubParkour v2.5 generated an exception while executing task 499412
java.lang.IllegalStateException: Asynchronous entity unregister!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-68]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2193) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2137) ~[?:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.stopTracking(PersistentEntitySectionManager.java:144) ~[patched_1.17.jar:git-Paper-68]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:436) ~[?:?]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:3903) ~[patched_1.17.jar:git-Paper-68]
        at com.gmail.filoghost.holographicdisplays.nms.v1_17_R1.EntityNMSArmorStand.killEntityNMS(EntityNMSArmorStand.java:205) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.line.CraftTextLine.despawn(CraftTextLine.java:115) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.object.CraftHologram.removeLine(CraftHologram.java:170) ~[?:?]
        at me.block2block.hubparkour.entities.LeaderboardHologram.refresh(LeaderboardHologram.java:68) ~[?:?]
        at me.block2block.hubparkour.entities.HubParkourPlayer$11.run(HubParkourPlayer.java:359) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-68]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-68]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-68]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Block2Block** [comment]
This error was fixed with update v2.5.1
